export const ActionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
    REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
    ADD_CARD: "ADD_CARD",
    ADD_CARD_REMOVE: "ADD_CARD_REMOVE",
    ADD_CARD_COUNT_PLUS: "ADD_CARD_COUNT_PLUS",
    ADD_CARD_COUNT_MINUS: "ADD_CARD_COUNT_MINUS",
    ADD_CARD_COUNT_DELETE: "ADD_CARD_COUNT_DELETE",
}